package com.example.demo;

import com.example.demo.entity.Employee;
import com.example.demo.repo.EmpRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;

@Configuration
@ComponentScan
public class Config {

    @Bean
    public CommandLineRunner insertRecords( final EmpRepository empRepository ) {
        return args -> {

            empRepository.save(new Employee( "Tama Kreps", "dept10" , 30));
            empRepository.save(new Employee( "Ambrose Kitamura", "dept11" , 31));
            empRepository.save(new Employee( "Adan Muir", "dept27" , 47));
            empRepository.save(new Employee( "Randall Hepfer", "dept16" , 51));
            empRepository.save(new Employee( "Theodora Guerrant", "dept16" , 52));
            empRepository.save(new Employee( "Lawerence Manville", "dept16" , 34));
            empRepository.save(new Employee( "Kristine Hartfield", "dept16" , 35));
            empRepository.save(new Employee( "Yuk Matta", "dept16" , 53));
            empRepository.save(new Employee( "Glennis Debo", "dept2"  , 22));
            empRepository.save(new Employee( "Elyse Kreider", "dept12" , 32));
            empRepository.save(new Employee( "Germaine Aronson", "dept9"  , 25));
            empRepository.save(new Employee( "Moshe Briggs", "dept16" , 36));
            empRepository.save(new Employee( "Troy Metheny", "dept9"  , 28));
            empRepository.save(new Employee( "Bernarda Poitras", "dept3" , 55));
            empRepository.save(new Employee( "Kattie Wolter", "dept1" , 38));
            empRepository.save(new Employee( "Lanora Lehmkuhl", "dept13" , 33));
            empRepository.save(new Employee( "Etta Poff", "dept9"  , 26));
            empRepository.save(new Employee( "Ligia Pasley", "dept9" , 41));
            empRepository.save(new Employee( "Marti Tesch", "dept9"  , 27));
            empRepository.save(new Employee( "Shantay Granata", "dept3"  , 23));
            empRepository.save(new Employee( "Dimple Illingworth", "dept26" , 46));
            empRepository.save(new Employee( "Edgar Knoblock", "dept16" , 54));
            empRepository.save(new Employee( "Rick Neher", "dept9"  , 21));
            empRepository.save(new Employee( "Christian Dumlao", "dept4"  , 24));
            empRepository.save(new Employee( "Josephina Rudman", "dept9" , 42));
            empRepository.save(new Employee( "Rina Locklear", "dept2" , 43));
            empRepository.save(new Employee( "Alise Allin", "dept9" , 48));
            empRepository.save(new Employee( "Tawanda Michaelson", "dept9" , 50));
            empRepository.save(new Employee( "Stephane Sidle", "dept9"  , 29));
            empRepository.save(new Employee( "Julieta Folden", "dept9" , 40));
            empRepository.save(new Employee( "Ciara Mendivil", "dept1" , 37));
            empRepository.save(new Employee( "Brunilda Vince", "dept2" , 44));
            empRepository.save(new Employee( "Lou Wisener", "dept1" , 39));
            empRepository.save(new Employee( "Galen Hargraves", "dept9" , 49));
            empRepository.save(new Employee( "Carina Spies", "dept2" , 45));


            empRepository.save(new Employee( "Tama Kreps", "dept10" , 30));
            empRepository.save(new Employee( "Ambrose Kitamura", "dept11" , 31));
            empRepository.save(new Employee( "Adan Muir", "dept27" , 47));
            empRepository.save(new Employee( "Randall Hepfer", "dept16" , 51));
            empRepository.save(new Employee( "Theodora Guerrant", "dept16" , 52));
            empRepository.save(new Employee( "Lawerence Manville", "dept16" , 34));
            empRepository.save(new Employee( "Kristine Hartfield", "dept16" , 35));
            empRepository.save(new Employee( "Yuk Matta", "dept16" , 53));
            empRepository.save(new Employee( "Glennis Debo", "dept2"  , 22));
            empRepository.save(new Employee( "Elyse Kreider", "dept12" , 32));
            empRepository.save(new Employee( "Germaine Aronson", "dept9"  , 25));
            empRepository.save(new Employee( "Moshe Briggs", "dept16" , 36));
            empRepository.save(new Employee( "Troy Metheny", "dept9"  , 28));
            empRepository.save(new Employee( "Bernarda Poitras", "dept3" , 55));
            empRepository.save(new Employee( "Kattie Wolter", "dept1" , 38));
            empRepository.save(new Employee( "Lanora Lehmkuhl", "dept13" , 33));
            empRepository.save(new Employee( "Etta Poff", "dept9"  , 26));
            empRepository.save(new Employee( "Ligia Pasley", "dept9" , 41));
            empRepository.save(new Employee( "Marti Tesch", "dept9"  , 27));
            empRepository.save(new Employee( "Shantay Granata", "dept3"  , 23));
            empRepository.save(new Employee( "Dimple Illingworth", "dept26" , 46));
            empRepository.save(new Employee( "Edgar Knoblock", "dept16" , 54));
            empRepository.save(new Employee( "Rick Neher", "dept9"  , 21));
            empRepository.save(new Employee( "Christian Dumlao", "dept4"  , 24));
            empRepository.save(new Employee( "Josephina Rudman", "dept9" , 42));
            empRepository.save(new Employee( "Rina Locklear", "dept2" , 43));
            empRepository.save(new Employee( "Alise Allin", "dept9" , 48));
            empRepository.save(new Employee( "Tawanda Michaelson", "dept9" , 50));
            empRepository.save(new Employee( "Stephane Sidle", "dept9"  , 29));
            empRepository.save(new Employee( "Julieta Folden", "dept9" , 40));
            empRepository.save(new Employee( "Ciara Mendivil", "dept1" , 37));
            empRepository.save(new Employee( "Brunilda Vince", "dept2" , 44));
            empRepository.save(new Employee( "Lou Wisener", "dept1" , 39));
            empRepository.save(new Employee( "Galen Hargraves", "dept9" , 49));
            empRepository.save(new Employee( "Carina Spies", "dept2" , 45));


            empRepository.save(new Employee( "Tama Kreps", "dept10" , 30));
            empRepository.save(new Employee( "Ambrose Kitamura", "dept11" , 31));
            empRepository.save(new Employee( "Adan Muir", "dept27" , 47));
            empRepository.save(new Employee( "Randall Hepfer", "dept16" , 51));
            empRepository.save(new Employee( "Theodora Guerrant", "dept16" , 52));
            empRepository.save(new Employee( "Lawerence Manville", "dept16" , 34));
            empRepository.save(new Employee( "Kristine Hartfield", "dept16" , 35));
            empRepository.save(new Employee( "Yuk Matta", "dept16" , 53));
            empRepository.save(new Employee( "Glennis Debo", "dept2"  , 22));
            empRepository.save(new Employee( "Elyse Kreider", "dept12" , 32));
            empRepository.save(new Employee( "Germaine Aronson", "dept9"  , 25));
            empRepository.save(new Employee( "Moshe Briggs", "dept16" , 36));
            empRepository.save(new Employee( "Troy Metheny", "dept9"  , 28));
            empRepository.save(new Employee( "Bernarda Poitras", "dept3" , 55));
            empRepository.save(new Employee( "Kattie Wolter", "dept1" , 38));
            empRepository.save(new Employee( "Lanora Lehmkuhl", "dept13" , 33));
            empRepository.save(new Employee( "Etta Poff", "dept9"  , 26));
            empRepository.save(new Employee( "Ligia Pasley", "dept9" , 41));
            empRepository.save(new Employee( "Marti Tesch", "dept9"  , 27));
            empRepository.save(new Employee( "Shantay Granata", "dept3"  , 23));
            empRepository.save(new Employee( "Dimple Illingworth", "dept26" , 46));
            empRepository.save(new Employee( "Edgar Knoblock", "dept16" , 54));
            empRepository.save(new Employee( "Rick Neher", "dept9"  , 21));
            empRepository.save(new Employee( "Christian Dumlao", "dept4"  , 24));
            empRepository.save(new Employee( "Josephina Rudman", "dept9" , 42));
            empRepository.save(new Employee( "Rina Locklear", "dept2" , 43));
            empRepository.save(new Employee( "Alise Allin", "dept9" , 48));
            empRepository.save(new Employee( "Tawanda Michaelson", "dept9" , 50));
            empRepository.save(new Employee( "Stephane Sidle", "dept9"  , 29));
            empRepository.save(new Employee( "Julieta Folden", "dept9" , 40));
            empRepository.save(new Employee( "Ciara Mendivil", "dept1" , 37));
            empRepository.save(new Employee( "Brunilda Vince", "dept2" , 44));
            empRepository.save(new Employee( "Lou Wisener", "dept1" , 39));
            empRepository.save(new Employee( "Galen Hargraves", "dept9" , 49));
            empRepository.save(new Employee( "Carina Spies", "dept2" , 45));

            empRepository.save(new Employee( "Veronica Glover", "dept10" , 30));
            empRepository.save(new Employee( "Zac Holt", "dept11" , 31));
            empRepository.save(new Employee( "Jaime Kay", "dept27" , 47));
            empRepository.save(new Employee( "Lili Key", "dept16" , 51));
            empRepository.save(new Employee( "Olivia-Mae Finley", "dept16" , 52));
            empRepository.save(new Employee( "Lillie-Rose Mendez", "dept16" , 34));
            empRepository.save(new Employee( "Brenna Sanford", "dept16" , 35));
            empRepository.save(new Employee( "Jenny Wells", "dept16" , 53));
            empRepository.save(new Employee( "Florrie Medina", "dept2"  , 22));
            empRepository.save(new Employee( "Milena Burris", "dept12" , 32));
            empRepository.save(new Employee( "Konrad Barry", "dept9"  , 25));
            empRepository.save(new Employee( "Nico Sharpe", "dept16" , 36));
            empRepository.save(new Employee( "Gwion Ingram", "dept9"  , 28));
            empRepository.save(new Employee( "Kameron Turnbull", "dept3" , 55));
            empRepository.save(new Employee( "Noel Pugh", "dept1" , 38));
            empRepository.save(new Employee( "Nawal Arroyo", "dept13" , 33));
            empRepository.save(new Employee( "Manisha O'Ryan", "dept9"  , 26));
            empRepository.save(new Employee( "Jaya Keith", "dept9" , 41));
            empRepository.save(new Employee( "Bibi Horton", "dept9"  , 27));
            empRepository.save(new Employee( "Maisy Jenkins", "dept3"  , 23));
            empRepository.save(new Employee( "Rida Mccray", "dept26" , 46));
            empRepository.save(new Employee( "Mcauley Blundell", "dept16" , 54));
            empRepository.save(new Employee( "Haaris Foster", "dept9"  , 21));
            empRepository.save(new Employee( "Ethel Miller", "dept4"  , 24));
            empRepository.save(new Employee( "Jeffrey Davila", "dept9" , 42));
            empRepository.save(new Employee( "Giles Prosser", "dept2" , 43));
            empRepository.save(new Employee( "Latisha Haney", "dept9" , 48));
            empRepository.save(new Employee( "Maksim Deacon", "dept9" , 50));
            empRepository.save(new Employee( "Giovanni Hull", "dept9"  , 29));
            empRepository.save(new Employee( "Marianne Adams", "dept9" , 40));
            empRepository.save(new Employee( "Jules Jackson", "dept1" , 37));
            empRepository.save(new Employee( "Ellesse Edge", "dept2" , 44));
            empRepository.save(new Employee( "Eira Holding", "dept1" , 39));
            empRepository.save(new Employee( "Freya Esquivel", "dept9" , 49));
            empRepository.save(new Employee( "Maxime Rice", "dept2" , 45));
            empRepository.save(new Employee( "Mariam Mcgill", "dept10" , 30));
            empRepository.save(new Employee( "Armani Chavez", "dept11" , 31));
            empRepository.save(new Employee( "Byron Boyd", "dept27" , 47));
            empRepository.save(new Employee( "Rudy Mccabe", "dept16" , 51));
            empRepository.save(new Employee( "Avleen Derrick", "dept16" , 52));
            empRepository.save(new Employee( "Nur Sykes", "dept16" , 34));
            empRepository.save(new Employee( "Aras Reyna", "dept16" , 35));
            empRepository.save(new Employee( "Lynsey Lynch", "dept16" , 53));
            empRepository.save(new Employee( "Chelsey Faulkner", "dept2"  , 22));
            empRepository.save(new Employee( "Laila Morrison", "dept12" , 32));
            empRepository.save(new Employee( "Chantal Walls", "dept9"  , 25));
            empRepository.save(new Employee( "Neal Dougherty", "dept16" , 36));
            empRepository.save(new Employee( "Zavier Booth", "dept9"  , 28));
            empRepository.save(new Employee( "Cassie Mullen", "dept3" , 55));
            empRepository.save(new Employee( "Ezmae Kirby", "dept1" , 38));
            empRepository.save(new Employee( "Mariya Gillespie", "dept13" , 33));
            empRepository.save(new Employee( "Alysha Atkinson", "dept9"  , 26));
            empRepository.save(new Employee( "Reiss Marsden", "dept9" , 41));
            empRepository.save(new Employee( "Zidan Berg", "dept9"  , 27));
            empRepository.save(new Employee( "Amalie Stephenson", "dept3"  , 23));
            empRepository.save(new Employee( "Liliana Kirkpatrick", "dept26" , 46));
            empRepository.save(new Employee( "Henrietta Haynes", "dept16" , 54));
            empRepository.save(new Employee( "Reema Sims", "dept9"  , 21));
            empRepository.save(new Employee( "Hashir Hastings", "dept4"  , 24));
            empRepository.save(new Employee( "Rafe Yoder", "dept9" , 42));
            empRepository.save(new Employee( "Meredith Goldsmith", "dept2" , 43));
            empRepository.save(new Employee( "Ava-May Leonard", "dept9" , 48));
            empRepository.save(new Employee( "Eman Watkins", "dept9" , 50));
            empRepository.save(new Employee( "Lacie Reeve", "dept9"  , 29));
            empRepository.save(new Employee( "Padraig Hook", "dept9" , 40));
            empRepository.save(new Employee( "Kelsie Wills", "dept1" , 37));
            empRepository.save(new Employee( "Kyla Alexander", "dept2" , 44));
            empRepository.save(new Employee( "Dixie Fuentes", "dept1" , 39));
            empRepository.save(new Employee( "Morgan Kerr", "dept9" , 49));
            empRepository.save(new Employee( "Nadeem Bender", "dept2" , 45));
            empRepository.save(new Employee( "Matilda Roberson", "dept2" , 43));
            empRepository.save(new Employee( "Arnav Humphries", "dept9" , 48));
            empRepository.save(new Employee( "Eleasha Rosario", "dept9" , 50));
            empRepository.save(new Employee( "Della Greenwood", "dept9"  , 29));
            empRepository.save(new Employee( "Finlay Vaughn", "dept9" , 40));
            empRepository.save(new Employee( "Emma Couch", "dept1" , 37));
            empRepository.save(new Employee( "Roberto Adam", "dept2" , 44));
            empRepository.save(new Employee( "Salim Saunders", "dept1" , 39));
            empRepository.save(new Employee( "Louis Hollis", "dept9" , 49));
            empRepository.save(new Employee( "Arnie Ferguson", "dept2" , 45));
            empRepository.save(new Employee( "Elysha Drummond", "dept2" , 43));
            empRepository.save(new Employee( "Harry Keeling", "dept9" , 48));
            empRepository.save(new Employee( "Fay Mac", "dept9" , 50));
            empRepository.save(new Employee( "Eliana Parks", "dept9"  , 29));
            empRepository.save(new Employee( "Joely Townsend", "dept9" , 40));
            empRepository.save(new Employee( "Alayah Chang", "dept1" , 37));
            empRepository.save(new Employee( "Youssef Field", "dept2" , 44));
            empRepository.save(new Employee( "Samah Cohen", "dept1" , 39));
            empRepository.save(new Employee( "Fatima Kearney", "dept9" , 49));
            empRepository.save(new Employee( "Kaylen O'Sullivan", "dept2" , 45));
            empRepository.save(new Employee( "Jagdeep Day", "dept2" , 43));
            empRepository.save(new Employee( "Jorja Whitehouse", "dept9" , 48));
            empRepository.save(new Employee( "Landon Morgan", "dept9" , 50));
            empRepository.save(new Employee( "Kishan Thompson", "dept9"  , 29));
            empRepository.save(new Employee( "Abida Kemp", "dept9" , 40));
            empRepository.save(new Employee( "Montana Booker", "dept1" , 37));
            empRepository.save(new Employee( "Juno Akhtar", "dept2" , 44));
            empRepository.save(new Employee( "Keith Stacey", "dept1" , 39));
            empRepository.save(new Employee( "Mabel Valdez", "dept9" , 49));
            empRepository.save(new Employee( "Michael Neal", "dept2" , 45));

        };
    }

}
